# Generated by Django 4.0.3 on 2022-03-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edito',
            new_name='Editor',
        ),
    ]
