# Generated by Django 4.0.3 on 2022-03-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_editor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='artice_image',
            field=models.ImageField(default='images/slide.jpg', upload_to='articles/'),
        ),
    ]
